### ISSUE TITLE
ldap account maneger (lam) showing blank..centos 7....

### ISSUE THREAD

**Issue by rajeshkumargond** [asaladino/ldap-debug-php#1]
==> error_log <==
[Tue Dec 26 15:18:40.477517 2017] [:error] [pid 5487] [client 10.31.32.219:39678] PHP Catchable fatal error:  Argument 1 passed to LAM\\LOGIN\\display_LoginPage() must be an instance of LAMConfig, null given, called in /var/www/html/lam/templates/login.php on line 609 and defined in /var/www/html/lam/templates/login.php on line 178

==> access_log <==
10.31.32.219 - - [26/Dec/2017:15:18:40 +0530] "GET /lam/templates/login.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
10.31.33.237 - - [26/Dec/2017:15:21:04 +0530] "GET /lam/ HTTP/1.1" 200 316 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

**Comment by rajeshkumargond** [comment]
please help on above issue

**Comment by asaladino** [comment]
Hello, I am unsure what the above error has to do with this project. This is project is just a small command line utility to assist in debugging php ldap connections and not for implementation on a site. Moreover, there is no class named LAMConfig in this project.

Wish I could help. Good luck.
